### ISSUE TITLE
Some Requests IDs missing, some request IDs repeating themselves

### ISSUE THREAD

**Issue by alwil** [TU-Delft-DCC/dcc_app#11]
Some of the projects don't have a request ID ( e.g.  line 33, 71,72)

some requests IDs ( within the same round) repeat themselves -  line 17, 18

**Comment by aecryan** [comment]
Duplicate IDs have been distinguished so that one contains _1. (line 17, 18).

**Comment by aecryan** [comment]
Lines 33, 71, 72 have new ids ending in _1 to show they were manually created.
