### ISSUE TITLE
Improve dashboard loading time

### ISSUE THREAD

**Issue by mwakok** [TU-Delft-DCC/dcc_app#55]
Building and serving the dashboard locally has the same loading delay as the deployed dashboard on shinyapps. This would mean it is not tied to hardware and moving it to a VPS would not improve the loading times. Instead, I think it is linked to rendering the dashboard and loading the data. This [guide](https://rmarkdown.rstudio.com/authoring_shiny_prerendered.HTML) provides solutions for pre-rendering the dashboard and caching the data.

**Comment by alwil** [comment]
- some of the packages were loaded, but not used. After the analysis with `funchir::stale_package_check('test.R')`*, I removed some of the unused packages, which reduced the local loading tiem from 30s to 12s. 

*As the function `stale_package_check()` accepts only `.R` scripts, `test.R` is the `dccapp.Rmd` file transformed to `test.R`.

I'll see if more improvements are feasible/ necessary.

**Comment by alwil** [comment]
- looked at the `runtime: shiny_prerendered` solution, but two of the graphs do not render: (see 8e18e057a49622f40d4246d1d27595777fe80275 ).
